// imports item class- creates data for menu-- this would come from an endpoint API 
import { Item } from './item';

export const MENUITEMS: Item[] = [
    { id: 1, name: 'Blue Point Oysters', price: 1.45, description: '', type: 'Raw Bar' },
    { id: 2, name: 'Martha\'s Vineyard Oysters', price: 2.25, description: '', type: 'Raw Bar' },
    { id: 3, name: 'Wellfleet Oysters', price: 2.25, description: '', type: 'Raw Bar' },
    { id: 4, name: 'Little Neck Clams', price: 1.35, description: '', type: 'Raw Bar' },
    { id: 5, name: 'Shrimp Cocktail', price: 9, description: '', type: 'Raw Bar' },
    { id: 6, name: 'New England Clam Chowder', price: 9, description: 'creamy chowder, fresh clams, potatoes, roasted garlic, bacon', type: 'soup' },
    { id: 7, name: 'Lobster Bisque', price: 9, description: 'smooth creamy lobster based bisque', type: 'soup' },
    { id: 8, name: 'Fish Market Soup', price: 9, description: 'sligthly spicy, hearty tomato, white fish, shrimp', type: 'soup' },
    { id: 9, name: 'Farmer\'s Scallop', price: 20, description: 'FRISEE, BACON, FINGERLING POTATOES, SUNNY SIDE UP EGG, LEMON & OLIVE OIL', type: 'salad' },
    { id: 10, name: 'Lobster Cobb', price: 25, description: 'LOBSTER, SHRIMP, GREENS, ONION, AVOCADO, BACON & LEMON HERB DRESSING', type: 'salad' },
    { id: 11, name: 'Grilled Octopus', price: 20, description: 'ARUGULA, BABY POTATOES, ROASTED PEPPERS, CAPERS, KALAMATA OLIVES, DILL VINAIGRETTE', type: 'salad' },
    { id: 12, name: 'King Crab Legs', price: 24, description: '1/2 LB steamed w/drawn butter', type: 'starter' },
    { id: 13, name: 'Crab Cake', price: 16, description: 'LUMP CRAB, TOMATOES, CHICK PEAS, ONIONS, CUCUMBER, ORANGE SEGMENTS, FRESH MINT, OLD BAY AIOLI', type: 'starter' },
    { id: 14, name: 'Wonton Tuna', price: 18, description: 'tuna, lemon zest, shallots, guacamole, chipotle aioli', type: 'starter' },
    { id: 15, name: 'Calamari', price: 14, description: 'grilled or fried, home-made marinare sauce', type: 'starter' },
    { id: 16, name: 'Twin Tartare', price: 16, description: 'tuna, salmon, home-made potato chips', type: 'starter' },
    { id: 17, name: 'Lobster Mac & Cheese', price: 19, description: '', type: 'starter' },
    { id: 18, name: 'Catfish Sandwich', price: 16, description: 'blackend or fried', type: 'fries on the side' },
    { id: 19, name: 'Lobster Roll', price: 21, description: 'hot lobster, garlic butter, brioche bun', type: 'fries on the side' },
    { id: 20, name: 'Fish & Chips', price: 18, description: 'british style', type: 'fries on the side' },
    { id: 21, name: 'Tuna Burger', price: 18, description: 'baby kale mison, pickled shallots', type: 'fries on the side' },
    { id: 22, name: 'Lobster Feast', price: 55, description: '1 1/4 LB whole main lobster, steamers, corn, fries', type: 'the works' },
    { id: 23, name: 'King Crab Legs', price: 42, description: '1 LB steamed w/drawn butter', type: 'the works' },
    { id: 24, name: 'Fisherman\'s Stew', price: 42, description: 'tomato based w/clams, shrimp, scallops, mussels, daily catch, 1/2 lobster', type: 'the works' },
    { id: 25, name: 'Crispy Skin Chilean Sea Bass', price: 36, description: 'jalapeno aioli, roasted season vegetables', type: 'the works' },
    { id: 26, name: 'Surf & Turf', price: 48, description: 'ottomanelli\'s 16 oz sirloin & half lobster, salad', type: 'the works' },
    { id: 27, name: 'Whole Branzino', price: 24, description: 'butterfly opened, capers, lemon, dill emulsion', type: 'the works' },
    { id: 28, name: 'Sauteed Spinach', price: 6, description: '', type: 'sides' },
    { id: 29, name: 'Green Beans', price: 6, description: '', type: 'sides' },
    { id: 30, name: 'Garlic Bread', price: 4, description: '', type: 'sides' },
    { id: 31, name: 'Rustic Mashed Potatoes', price: 6, description: '', type: 'sides' },
    { id: 28, name: 'French Fries', price: 6, description: '', type: 'sides' },
];
